# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=6)),
                ('em', models.CharField(max_length=30)),
                ('cn', models.CharField(max_length=20)),
                ('rl', models.CharField(max_length=20)),
                ('ic', models.FileField(upload_to='')),
                ('is_admin', models.BooleanField(default=False)),
                ('pe', models.IntegerField(max_length=3)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
