# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us',
            name='pe',
            field=models.CharField(max_length=3),
        ),
    ]
