# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_auto_20190224_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='us',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
