# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_auto_20190224_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='us',
            old_name='uid',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='us',
            name='ic',
            field=models.FileField(upload_to='media/'),
        ),
    ]
