# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fs', '0004_auto_20190224_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us',
            name='password',
        ),
        migrations.RemoveField(
            model_name='us',
            name='username',
        ),
        migrations.AddField(
            model_name='us',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
