# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_auto_20190225_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us',
            old_name='is_active',
            new_name='is_act',
        ),
        migrations.RenameField(
            model_name='us',
            old_name='is_admin',
            new_name='is_ad',
        ),
    ]
