# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_auto_20190225_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='sug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EC', models.CharField(max_length=50)),
                ('EN', models.CharField(max_length=50)),
                ('S', models.CharField(max_length=50)),
            ],
        ),
    ]
