# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0009_sug_er'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sug',
            name='EN',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sug',
            name='ER',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sug',
            name='S',
            field=models.CharField(max_length=500),
        ),
    ]
