# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0010_auto_20190413_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='fn',
            field=models.CharField(default='vishal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='us',
            name='ln',
            field=models.CharField(default='vishal', max_length=20),
            preserve_default=False,
        ),
    ]
